### ISSUE TITLE
What fonts are these?

### ISSUE THREAD

**Issue by karlp** [emacsfodder/dark-tooth-wasd#1]
Unfortunately it seems all your keys were converted to paths or something, I quite like the look of this keyboard, but I need to adjust it for 105key euro layout and add some þðæö chars.

**Comment by jasonm23** [comment]
Font is Gotham Rounded.  I cannot supply it. (Licence issue)

WASD do not accept SVG with non standard fonts, which is why it's set as outlines.

**Comment by karlp** [comment]
thanks
